require('dotenv').config();
const express = require('express');
const mongoose = require('mongoose');
const helmet = require('helmet');
const cors = require('cors');
const morgan = require('morgan');
const authRoutes = require('./src/routes/auth');
const txnRoutes = require('./src/routes/transactions');
const app = express();
const PORT = process.env.PORT || 4000;
app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(morgan('dev'));
app.use('/api/auth', authRoutes);
app.use('/api/transactions', txnRoutes);
app.get('/', (req, res) => res.json({status: 'SmartFinance backend running'}));
mongoose.connect(process.env.MONGO_URI).then(()=> app.listen(PORT, ()=> console.log(`Backend listening on ${PORT}`))).catch(err => console.error('Mongo error', err));
